language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - yarn build
deploy:
  provider: surge
  skip_cleanup: true
  domain: http://mv-virtual-wallet.surge.sh
  project: ./build/
env:
  - REACT_APP_BUILD_ENV=prd
branchs: 
  except:
  - dev
  only: 
  - master
